### ISSUE TITLE
Doesn't work on the root page

### ISSUE THREAD

**Issue by utsushiiro** [weseek/growi-plugin-attachment-refs#2]
ルートページにて以下のように指定した場合,

```
$ref(something.png)
```

画像が表示されず, 以下のようなエラーメッセージが表示される.
![スクリーンショット 2020-06-20 21 29 51](https://user-images.githubusercontent.com/20026847/85201857-72493a00-b33d-11ea-98ba-f1873c9ff245.png)

getAbsolutePathFor の中で呼んでいる pathUtils.normalizePathが `'/'` を渡された際に `'//'` を返してしまっていることが原因.
https://github.com/weseek/growi-plugin-attachment-refs/blob/8683a9104d71b1cfd8e9c2dfd1127039f878d8bd/src/client/js/util/RefsContext.js#L235-L246

**Comment by yuki-takei** [comment]
growi-commons@5.0.3 をリリースした

**Comment by utsushiiro** [comment]
v1.1.1で解消を確認できたためClose
